name: cicd

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  format:
    name: format
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: portfolio

    steps:
      - name: format
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier (fix)
        run: npm run format:fix
  lint:
    name: lint
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: portfolio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (check only)
        run: npm run lint:check
  test:
    name: test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: portfolio

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Run Vitest
        run: npm run test:coverage
  deploy:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    name: deploy
    defaults:
      run:
        working-directory: portfolio

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./portfolio/dist